from .books import *  # noqa
from .genre import *  # noqa
from .info import *  # noqa
from .news import *  # noqa
from .notification import *  # noqa
from .order import *  # noqa
from .partners import *  # noqa
from .videos import *  # noqa
from .test import *  # noqa
