# Generated by Django 5.0.8 on 2024-12-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz_Cyrl",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Book Category",
                "verbose_name_plural": "Book Categories",
                "db_table": "books_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz_Cyrl",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "db_table": "genre",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz_Cyrl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_uz_Cyrl",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Info",
                "verbose_name_plural": "Infos",
                "db_table": "info",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz_Cyrl",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "News Category",
                "verbose_name_plural": "News Categories",
                "db_table": "news_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banner",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="notifications",
                        verbose_name="Banner",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz_Cyrl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                ("message", models.TextField(db_index=True, verbose_name="Message")),
                (
                    "message_uz",
                    models.TextField(db_index=True, null=True, verbose_name="Message"),
                ),
                (
                    "message_ru",
                    models.TextField(db_index=True, null=True, verbose_name="Message"),
                ),
                (
                    "message_en",
                    models.TextField(db_index=True, null=True, verbose_name="Message"),
                ),
                (
                    "message_uz_Cyrl",
                    models.TextField(db_index=True, null=True, verbose_name="Message"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("SINGLE", "Single"), ("ALL", "All")],
                        default="SINGLE",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("is_send", models.BooleanField(default=False, verbose_name="Is Send")),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("ELECTRONIC", "Electronic"),
                            ("PHYSICAL", "Physical"),
                        ],
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "address",
                    models.JSONField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "payment_status",
                    models.BooleanField(default=False, verbose_name="Payment Status"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="Total Price"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                            ("OCTO", "OCTO"),
                            ("CASH", "Cash"),
                        ],
                        default="PAYME",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz_Cyrl",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tags",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz_Cyrl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_uz_Cyrl",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(upload_to="videos/banner", verbose_name="Banner"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "original_file",
                    models.FileField(
                        upload_to="videos/original", verbose_name="Original File"
                    ),
                ),
                (
                    "view_count",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="View Count"
                    ),
                ),
                (
                    "hls_playlist",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/hls_playlist",
                        verbose_name="HLS Playlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "db_table": "video",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz_Cyrl",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Video Category",
                "verbose_name_plural": "Video Categories",
                "db_table": "video_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz_Cyrl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "sub_title_uz",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "sub_title_ru",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "sub_title_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "sub_title_uz_Cyrl",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_uz_Cyrl",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Author"
                    ),
                ),
                (
                    "author_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Author"
                    ),
                ),
                (
                    "author_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Author"
                    ),
                ),
                (
                    "author_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Author"
                    ),
                ),
                (
                    "author_uz_Cyrl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Author"
                    ),
                ),
                ("banner", models.ImageField(upload_to="books", verbose_name="Banner")),
                ("pages", models.BigIntegerField(verbose_name="Pages")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="Price"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        null=True,
                        verbose_name="Discount Price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("file", models.FileField(upload_to="books", verbose_name="File")),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="books/original",
                        verbose_name="Original File",
                    ),
                ),
                (
                    "sold_count",
                    models.BigIntegerField(default=0, verbose_name="Sold Count"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="hidaya.bookcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="books", to="hidaya.genre", verbose_name="Genre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "book",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz_Cyrl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "sub_title_uz",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "sub_title_ru",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "sub_title_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "sub_title_uz_Cyrl",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_uz_Cyrl",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                ("banner", models.ImageField(upload_to="news", verbose_name="Banner")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "view_count",
                    models.BigIntegerField(default=0, verbose_name="View Count"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="hidaya.newscategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "db_table": "news",
                "ordering": ["-created_at"],
            },
        ),
    ]
