# Generated by Django 5.0.8 on 2024-12-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="hls_playlist",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/hls_playlist",
                verbose_name="HLS Playlist",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="view_count",
            field=models.BigIntegerField(
                default=0, editable=False, verbose_name="View Count"
            ),
        ),
    ]
