# Generated by Django 5.0.8 on 2024-12-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0004_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_uz_Cyrl",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
