# Generated by Django 5.0.8 on 2024-12-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0006_video_type_video_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="books", verbose_name="File"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="original_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/original",
                verbose_name="Original File",
            ),
        ),
    ]
