# Generated by Django 5.0.8 on 2024-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0007_alter_book_file_alter_video_original_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logo", models.ImageField(upload_to="platforms", verbose_name="Logo")),
                ("text", models.TextField(verbose_name="Text")),
                ("text_uz", models.TextField(null=True, verbose_name="Text")),
                ("text_ru", models.TextField(null=True, verbose_name="Text")),
                ("text_en", models.TextField(null=True, verbose_name="Text")),
                ("text_uz_Cyrl", models.TextField(null=True, verbose_name="Text")),
                (
                    "image",
                    models.ImageField(upload_to="platforms", verbose_name="Image"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz_Cyrl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_uz",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_uz_Cyrl",
                    models.TextField(null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
                "db_table": "platform",
                "ordering": ["-created_at"],
            },
        ),
    ]
