# Generated by Django 5.0.8 on 2024-12-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0010_rename_author_uz_cyrl_book_author_ko_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_url",
        ),
        migrations.AddField(
            model_name="video",
            name="iframe",
            field=models.TextField(blank=True, null=True, verbose_name="Iframe"),
        ),
    ]
