# Generated by Django 5.0.8 on 2025-01-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0013_question_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="buy_link",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Buy Link",
            ),
        ),
    ]
