# Generated by Django 5.0.8 on 2025-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0014_book_buy_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer_en",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="answer",
            name="answer_ko",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="answer",
            name="answer_tr",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="answer",
            name="answer_uz",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_en",
            field=models.TextField(null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_ko",
            field=models.TextField(null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_tr",
            field=models.TextField(null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_uz",
            field=models.TextField(null=True, verbose_name="Question"),
        ),
    ]
