# Generated by Django 5.0.8 on 2025-01-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0015_answer_answer_en_answer_answer_ko_answer_answer_tr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_en",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_ko",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_tr",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_uz",
            field=models.TextField(null=True),
        ),
    ]
