# Generated by Django 5.0.8 on 2025-01-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0016_alter_answer_answer_alter_answer_answer_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Link",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(upload_to="latest_news", verbose_name="Banner"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Latest News",
                "verbose_name_plural": "Latest News",
                "db_table": "latest_news",
                "ordering": ("-created_at",),
            },
        ),
    ]
