# Generated by Django 5.0.8 on 2025-01-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0017_latestnews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestnews",
            name="banner",
            field=models.ImageField(upload_to="latest_news", verbose_name="Image 16:9"),
        ),
    ]
