# Generated by Django 5.0.8 on 2025-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0019_remove_notification_is_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Link"
            ),
        ),
    ]
