# Generated by Django 5.0.8 on 2025-01-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hidaya", "0020_news_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Switcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Switcher",
                "verbose_name_plural": "Switchers",
                "db_table": "switchers",
            },
        ),
    ]
