from django.urls import path

from apps.hidaya.views import (
    # PaymeCallBackAPIView,
    # OrderCreate,
    BookList,
    BookDetail,
    NewsDetail,
    NewsList,
    InfoList,
    InfoDetail,
    BookCategoryList,
    NewsCategoryList,
    VideoCategoryList,
    VideoList,
    VideoDetail,
    GetSignedVideoURLView,
    NotificationView,
    PartnerList,
    PlatformList,
    AuthorList, QuestionList, TestResult,
)

urlpatterns = [
    # path("merchant/payme/", PaymeCallBackAPIView.as_view(), name="payme-callback"),
    # path("order/", OrderCreate.as_view(), name="order-create"),
    path("book/", BookList.as_view(), name="book-list"),
    path("book/<int:pk>/", BookDetail.as_view(), name="book-detail"),
    path("news/", NewsList.as_view(), name="news-list"),
    path("news/<int:pk>/", NewsDetail.as_view(), name="news-detail"),
    path("video/", VideoList.as_view(), name="video-list"),
    path("video/<int:pk>/", VideoDetail.as_view(), name="video-detail"),
    path("info/", InfoList.as_view(), name="info-list"),
    path("info/<int:pk>/", InfoDetail.as_view(), name="info-detail"),
    path("partner/", PartnerList.as_view(), name="partner-list"),
    path("platform/", PlatformList.as_view(), name="platform-list"),
    path("author/", AuthorList.as_view(), name="author-list"),
    path("test/<int:pk>/<int:qty>/", QuestionList.as_view(), name="test-list"),
    path("test/result/", TestResult.as_view(), name="test-result"),
    path("category/book/", BookCategoryList.as_view(), name="category-book-list"),
    path("category/news/", NewsCategoryList.as_view(), name="category-news-list"),
    path("category/video/", VideoCategoryList.as_view(), name="category-video-list"),
    path("notifications/", NotificationView.as_view(), name="notifications"),
    path(
        "videos/<int:video_id>/<str:quality>/<str:file_name>/signed-url/",
        GetSignedVideoURLView.as_view(),
        name="get_signed_video_url",
    ),
]
